# theme: jekyll-theme-myst729

sass:
  style: :compressed

plugins:
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

title: dg
typeof: Object.prototype.toString.call(dg)
tagline: '"[object WebDev]"'
baseurl: /
herolink: posts
excerpt_separator: <!-- more -->
repository: myst729/myst729.github.io

avatar:
  png: /assets/avatar.png
  svg: /assets/avatar.svg
  anim: /assets/avatar-animation.svg

social:
  github: https://github.com/myst729
  stackoverflow: https://stackoverflow.com/users/1032492

social-deprecated:
  weibo: https://weibo.com/myst729
